# Generated by Django 4.1.1 on 2022-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('show_url', models.TextField(blank=True, null=True)),
                ('season_title', models.TextField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.TextField(blank=True, null=True)),
                ('episode_title', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('url_title', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.TextField(blank=True, null=True)),
                ('show_title', models.TextField(blank=True, null=True)),
                ('show_picurl', models.TextField(blank=True, db_column='show_picUrl', null=True)),
                ('show_counts', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shows',
                'managed': False,
            },
        ),
    ]
